# Pandas

데이터 세트을 분석하고 처리하기 위해 개발된 파이썬 외부 모듈이다.  
일반적으로 테이블 형태의 데이터를 빠르게 처리하기 위해 설계되어 있다.  

```bash
pip install pandas
pip install openpyxl
```

- Series : 하나의 열(Column) 데이터를 표현(저장)하기위 설계된 클래스이다.
- DataFrame : 테이블 데이터를 표현(저장)하기위해 설계된 클래스이다.

In [1]:
import pandas as pd

## Series

In [2]:
li = [10, 20, 30, 40, 50]
s = pd.Series(li)
print(s)

0    10
1    20
2    30
3    40
4    50
dtype: int64

In [3]:
li = ['사과', '배', '바나나', '포도', '수박']
fr = pd.Series(li)
print(fr)

0     사과
1      배
2    바나나
3     포도
4     수박
dtype: object

In [4]:
# 시리즈 데이터의 접근
print(fr[0])
print(fr[1])

사과
배

In [5]:
di = {0:'사과', 1:'배', 2:'포도'}
print(di[2])
print(di[0])

포도
사과

In [6]:
li = ['사과', '배', '바나나', '포도', '수박']
fr = pd.Series(li, index=['a', 'b', 'c', 'd', 'e'])
print(fr)

a     사과
b      배
c    바나나
d     포도
e     수박
dtype: object

In [7]:
print(fr['c'])

바나나

In [8]:
di = {'a':'사과', 'b':'바나나', 'c':'포도', 'd':'수박'}
fr = pd.Series(di)
print(fr)

a     사과
b    바나나
c     포도
d     수박
dtype: object

In [9]:
# 수정하기: 이미 존재하는 키를 이용하여 데이터를 대입
fr['a'] = '귤'
fr

a      귤
b    바나나
c     포도
d     수박
dtype: object

In [10]:
# 입력하기: 없는 키에 데이터를 대입하면 추가
fr['e'] = '딸기'
fr

a      귤
b    바나나
c     포도
d     수박
e     딸기
dtype: object

In [ ]:
# 삭제하기
fr_drop = fr.drop('a')
fr_drop

b    바나나
c     포도
d     수박
e     딸기
dtype: object

In [12]:
# csv 파일을 읽어서 데이터프레임 객체에 데이터를 로딩한다.
df = pd.read_csv('data.csv')
df

     Duration  Pulse  Maxpulse  Calories
0          60    110       130     409.1
1          60    117       145     479.0
2          60    103       135     340.0
3          45    109       175     282.4
4          45    117       148     406.0
..        ...    ...       ...       ...
164        60    105       140     290.8
165        60    110       145     300.0
166        60    115       145     310.2
167        75    120       150     320.4
168        75    125       150     330.4

[169 rows x 4 columns]

In [ ]:
# openpyxl 이 설치되어 있어야 정상적으로 동작한다.
# df = pd.read_exel('파일경로명')

# df = pd.read_json('파일경로명')

In [13]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [14]:
# 기본 통계정보 확인하기
df.describe()

         Duration       Pulse    Maxpulse     Calories
count  169.000000  169.000000  169.000000   164.000000
mean    63.846154  107.461538  134.047337   375.790244
std     42.299949   14.510259   16.450434   266.379919
min     15.000000   80.000000  100.000000    50.300000
25%     45.000000  100.000000  124.000000   250.925000
50%     60.000000  105.000000  131.000000   318.600000
75%     60.000000  111.000000  141.000000   387.600000
max    300.000000  159.000000  184.000000  1860.400000

In [ ]:
# 각 컬럼들의 상관관계 정보를 알려준다
# 상관관계: -1 ~ 0 ~ 1

df.corr()

          Duration     Pulse  Maxpulse  Calories
Duration  1.000000 -0.155408  0.009403  0.922717
Pulse    -0.155408  1.000000  0.786535  0.025121
Maxpulse  0.009403  0.786535  1.000000  0.203813
Calories  0.922717  0.025121  0.203813  1.000000

In [16]:
# 결측치 데이터 처리하기
# 결측치 데이터 삭제하기
df_new = df.dropna()
df_new.info()

<class 'pandas.core.frame.DataFrame'>
Index: 164 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  164 non-null    int64
 1   Pulse     164 non-null    int64
 2   Maxpulse  164 non-null    int64
 3   Calories  164 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 6.4 KB

In [19]:
avg = df['Calories'].mean()
avg

df_new = df.fillna(avg)
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  169 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB

In [ ]:
df_new = df.fillna({'Calories':avg})
df_new.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 169 entries, 0 to 168
Data columns (total 4 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   Duration  169 non-null    int64
 1   Pulse     169 non-null    int64
 2   Maxpulse  169 non-null    int64
 3   Calories  169 non-null    float64
dtypes: float64(1), int64(3)
memory usage: 5.4 KB